// @ts-check
import starlight from '@astrojs/starlight';
import { defineConfig } from 'astro/config';
import starlightLinksValidator from 'starlight-links-validator';
import starlightSidebarTopics from 'starlight-sidebar-topics';

/**
 * Sidebar group helper: an autogenerated group for one folder, with a Greek
 * label (source language) and its English translation.
 *
 * @param {string} el Greek label
 * @param {string} en English label
 * @param {string} directory folder under src/content/docs/
 */
const section = (el, en, directory) => ({
	label: el,
	translations: { en },
	items: [{ autogenerate: { directory } }],
});

export default defineConfig({
	site: 'https://docs.lynk.gr',
	integrations: [
		starlight({
			title: { el: 'Τεκμηρίωση Lynk', en: 'Lynk docs' },
			description: 'Οδηγοί και απαντήσεις για τις εφαρμογές της Lynk.',
			defaultLocale: 'root',
			locales: {
				root: { label: 'Ελληνικά', lang: 'el' },
				en: { label: 'English', lang: 'en' },
			},
			logo: {
				light: './src/assets/lynk-logo-light.svg',
				dark: './src/assets/lynk-logo-dark.svg',
				alt: 'Lynk',
				replacesTitle: true,
			},
			favicon: '/favicon.svg',
			customCss: ['./src/styles/theme.css'],
			components: {
				// Light theme by default; dark and auto stay available in the picker.
				ThemeProvider: './src/components/ThemeProvider.astro',
			},
			pagefind: true,
			plugins: [
				starlightLinksValidator({
					errorOnInconsistentLocale: true,
				}),
				// Each Lynk product is one topic. See CONTRIBUTING.md, "Adding a product topic".
				starlightSidebarTopics(
					[
						{
							id: 'insights',
							label: { el: 'Lynk Insights', en: 'Lynk Insights' },
							link: '/insights/',
							icon: 'analytics',
							items: [
								{ slug: 'insights', label: 'Επισκόπηση', translations: { en: 'Overview' } },
								{
									slug: 'insights/whats-new',
									label: 'Τι νέο υπάρχει',
									translations: { en: "What's new" },
								},
								section('Ξεκινώντας', 'Getting started', 'insights/getting-started'),
								section('Κανάλια', 'Channels', 'insights/channels'),
								section('Softone ERP', 'Softone ERP', 'insights/softone'),
								section('Κέρδη & κόστη', 'Profit & costs', 'insights/profit-costs'),
								section('Παραγγελίες', 'Orders', 'insights/orders'),
								section('Αυτοματισμοί', 'Automations', 'insights/automations'),
								section('Ομάδα & λογαριασμός', 'Team & account', 'insights/team'),
								section(
									'Αντιμετώπιση προβλημάτων',
									'Troubleshooting',
									'insights/troubleshooting',
								),
								section('Συχνές ερωτήσεις', 'FAQ', 'insights/faq'),
								section('Γλωσσάρι', 'Glossary', 'insights/glossary'),
							],
						},
						{
							id: 'account',
							label: { el: 'Λογαριασμός', en: 'Account' },
							link: '/account/',
							icon: 'setting',
							items: [{ autogenerate: { directory: 'account' } }],
						},
					],
					{
						// The splash home pages belong to no topic.
						exclude: ['/', '/en/'],
					},
				),
			],
		}),
	],
});
